services:
  app1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    container_name: react-app1
    restart: unless-stopped

  # app2:
  #   build:
  #     context: ./Cogniflow-Front-Copy/CogniFlow-Front/mega-plate
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3002:80"
  #   container_name: react-app2
  #   restart: unless-stopped

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
#      - app2
    restart: unless-stopped
